server:
  port: 8080


#通用数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://nwcdpicture.cvoatjsakg94.us-east-1.rds.amazonaws.com:3306/tb_user?useUnicode=true&characterEncoding=utf-8
    username: nwcduser
    password: 1234%^&*
# JPA 相关配置
  jpa:
    show-sql: false
  serlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 30Mb
      max-request-size: 30Mb